import { BambooField } from '../lib/types';
import { TaylorTypeGenerator } from './taylor-type-generator';

export class TypeMapper {
  constructor(private readonly taylorTypeGenerator: TaylorTypeGenerator) {}

  map(column: BambooField) {
    const isRequired = column.options['isRequired'] === true;

    switch (column.type) {
      case 'singleLineText':
      case 'text':
      case 'json':
      case 'url':
      case 'email':
      case 'phoneNumber':
      case 'longText':
        return `TextColumnType<${isRequired ? 'true' : 'false'}>`;

      case 'autoNumber':
        return `AutoGeneratedNumberColumnType`;

      case 'number':
      case 'position':
      case 'percent':
      case 'duration':
      case 'decimalSerial':
      case 'serial':
        return `NumberColumnType<${isRequired ? 'true' : 'false'}>`;

      case 'checkbox':
        return 'CheckboxColumnType';

      case 'link':
        return `LinkColumnType<'${this.findNameBySlug(column.options.on)}', ${isRequired ? 'true' : 'false'}>`;

      case 'modifiedBy':
      case 'collaborators':
        return `LinkColumnType<'collaboratorsTable', ${isRequired ? 'true' : 'false'}>`;

      case 'attachment':
        return `LinkColumnType<'attachmentTable', ${isRequired ? 'true' : 'false'}>`;

      case 'select':
        return `LinkColumnType<'selectTable', ${isRequired ? 'true' : 'false'}>`;

      case 'createdAt':
      case 'updatedAt':
      case 'modifiedAt':
        return `AutoGeneratedDateColumnType`;

      case 'date':
        return `DateColumnType<${isRequired ? 'true' : 'false'}>`;

      default:
        return null;
    }
  }

  private findNameBySlug(slug: string) {
    const table = this.taylorTypeGenerator.tablesSchema.find(
      table => table.slug === slug,
    );

    if (!table) {
      throw new Error(`Table with slug ${slug} not found`);
    }

    return table.name;
  }
}
