import { BambooField } from '../lib/types';
import { TaylorTypeGenerator } from './taylor-type-generator';

export class TypeMapper {
  constructor(
    private readonly taylorTypeGenerator: TaylorTypeGenerator,
    private readonly optionsMap: Map<string, { id: number; name: string }[]>,
  ) {}

  map(column: BambooField) {
    const isRequired = column.options['isRequired'] === true;

    switch (column.type) {
      case 'singleLineText':
      case 'text':
      case 'json':
      case 'url':
      case 'email':
      case 'phoneNumber':
      case 'longText':
        return `TextColumnType<${isRequired ? 'true' : 'false'}>`;

      case 'autoNumber':
        return `AutoGeneratedNumberColumnType`;

      case 'number':
      case 'position':
      case 'percent':
      case 'duration':
      case 'decimalSerial':
      case 'serial':
      case 'currency':
        return `NumberColumnType<${isRequired ? 'true' : 'false'}>`;

      case 'checkbox':
        return `CheckboxColumnType<${isRequired ? 'true' : 'false'}>`;

      case 'link':
        return `LinkColumnType<'${this.findNameBySlug(column.options.on)}', ${isRequired ? 'true' : 'false'}>`;

      case 'modifiedBy':
      case 'collaborators':
        return `LinkColumnType<'collaborators', ${isRequired ? 'true' : 'false'}>`;

      case 'attachment':
        return `AttachmentColumnType<${isRequired ? 'true' : 'false'}>`;

      case 'search':
        return `SearchColumnType<${isRequired ? 'true' : 'false'}>`;

      case 'select': {
        const options = this.optionsMap.get(column.options.on);

        if (options) {
          const tableName = this.taylorTypeGenerator.tablesSchema.find(table =>
            table.fields.some(field => field.id === column.id),
          )!.name;

          const constName = this.taylorTypeGenerator.getSingleSelectConstName(
            tableName,
            column.name,
          );
          const typeName = column.options['isSingle']
            ? 'SingleSelectColumnType'
            : 'MultiSelectColumnType';
          return `${typeName}<typeof ${constName}, ${
            isRequired ? 'true' : 'false'
          }>`;
        }

        return `LinkColumnType<'selectTable', ${
          isRequired ? 'true' : 'false'
        }>`;
      }

      case 'createdAt':
      case 'updatedAt':
      case 'modifiedAt':
        return `AutoGeneratedDateColumnType`;

      case 'date':
        return `DateColumnType<${isRequired ? 'true' : 'false'}>`;

      default: {
        switch (column.returnType) {
          case 'string':
            return `TextColumnType<${isRequired ? 'true' : 'false'}>`;

          case 'number':
            return `NumberColumnType<${isRequired ? 'true' : 'false'}>`;

          case 'boolean':
            return `CheckboxColumnType<${isRequired ? 'true' : 'false'}>`;

          case 'date':
            return `DateColumnType<${isRequired ? 'true' : 'false'}>`;

          default:
            return null;
        }
      }
    }
  }

  private findNameBySlug(slug: string) {
    const table = this.taylorTypeGenerator.tablesSchema.find(
      table => table.slug === slug,
    );

    if (!table) {
      throw new Error(`Table with slug ${slug} not found`);
    }

    return table.name;
  }
}
