import {
  AttachmentColumnType,
  AutoGeneratedDateColumnType,
  AutoGeneratedNumberColumnType,
  CheckboxColumnType,
  ColumnType,
  DateColumnType,
  LinkColumnType,
  MultiSelectColumnType,
  NumberColumnType,
  SearchColumnType,
  SingleSelectColumnType,
  TextColumnType,
} from './column-types.js';

export type BambooFieldsType =
  | 'json'
  | 'number'
  | 'date'
  | 'modifiedAt'
  | 'link'
  | 'currency'
  | 'percent'
  | 'url'
  | 'email'
  | 'phoneNumber'
  | 'checkbox'
  | 'select'
  | 'count'
  | 'autoNumber'
  | 'formula'
  | 'position'
  | 'rating'
  | 'createdAt'
  | 'updatedAt'
  | 'singleLineText'
  | 'text'
  | 'longText'
  | 'lookup'
  | 'rollup'
  | 'collaborators'
  | 'modifiedBy'
  | 'duration'
  | 'createdBy'
  | 'attachment'
  | 'button';

export const exposingFieldTypes = [
  'json',
  'number',
  'date',
  'modifiedAt',
  'link',
  'currency',
  'percent',
  'url',
  'email',
  'phoneNumber',
  'checkbox',
  'select',
  'count',
  'autoNumber',
  'formula',
  'position',
  'rating',
  'createdAt',
  'updatedAt',
  'singleLineText',
  'text',
  'longText',
  'lookup',
  'rollup',
  'collaborators',
  'modifiedBy',
  'duration',
  'createdBy',
  'attachment',
  'button',
] as const satisfies readonly BambooFieldsType[];

type RequiredOption<R extends boolean = boolean> = {
  required: R;
};

type ComputedReturnType = 'string' | 'json' | 'select' | 'number' | 'boolean' | 'date';

type BaseFieldDescriptor<
  TType extends string,
  R extends boolean,
  TInsertable extends boolean,
  TUpdatable extends boolean,
> = {
  type: TType;
  required: R;
  insertable: TInsertable;
  updatable: TUpdatable;
};

type TextLikeFieldType =
  | 'json'
  | 'url'
  | 'email'
  | 'phoneNumber'
  | 'singleLineText'
  | 'text'
  | 'longText'
  | 'button';

type NumberLikeFieldType =
  | 'number'
  | 'currency'
  | 'percent'
  | 'count'
  | 'position'
  | 'rating'
  | 'duration';

type SystemDateFieldType = 'createdAt' | 'updatedAt' | 'modifiedAt' | 'autoDate';
type CollaboratorLinkFieldType = 'collaborators' | 'modifiedBy' | 'createdBy';
type ComputedFieldType = 'formula' | 'lookup' | 'rollup';

export type TextFieldDescriptor<
  R extends boolean = boolean,
  TType extends TextLikeFieldType = 'text',
> = BaseFieldDescriptor<TType, R, true, true>;

export type NumberFieldDescriptor<
  R extends boolean = boolean,
  TType extends NumberLikeFieldType = 'number',
> = BaseFieldDescriptor<TType, R, true, true>;

export type CheckboxFieldDescriptor<R extends boolean = boolean> =
  BaseFieldDescriptor<'checkbox', R, true, true>;

export type DateFieldDescriptor<R extends boolean = boolean> =
  BaseFieldDescriptor<'date', R, true, true>;

export type SearchFieldDescriptor = BaseFieldDescriptor<
  'search',
  false,
  true,
  true
>;

export type LinkFieldDescriptor<
  TLinkedTo extends string = string,
  R extends boolean = boolean,
  TType extends 'link' | CollaboratorLinkFieldType = 'link',
> = BaseFieldDescriptor<TType, R, true, true> & {
  linkedTo: TLinkedTo;
};

export type AttachmentFieldDescriptor<R extends boolean = boolean> =
  BaseFieldDescriptor<'attachment', R, true, true> & {
    linkedTo: 'attachmentTable';
  };

export type SelectFieldDescriptor<
  TOptions extends readonly string[] = readonly string[],
  R extends boolean = boolean,
  TMode extends 'single' | 'multi' = 'single' | 'multi',
> = BaseFieldDescriptor<'select', R, true, true> & {
  mode: TMode;
  options: TOptions;
};

export type AutoNumberFieldDescriptor = BaseFieldDescriptor<
  'autoNumber',
  false,
  false,
  false
>;

export type AutoDateFieldDescriptor<
  TType extends SystemDateFieldType = 'autoDate',
> = BaseFieldDescriptor<
  TType,
  false,
  false,
  false
>;

export type ComputedFieldDescriptor<
  TType extends ComputedFieldType = ComputedFieldType,
  TReturnType extends ComputedReturnType = ComputedReturnType,
> = BaseFieldDescriptor<TType, false, false, false> & {
  returnType: TReturnType;
};

export type JsonFieldDescriptor<R extends boolean = boolean> =
  TextFieldDescriptor<R, 'json'>;
export type UrlFieldDescriptor<R extends boolean = boolean> =
  TextFieldDescriptor<R, 'url'>;
export type EmailFieldDescriptor<R extends boolean = boolean> =
  TextFieldDescriptor<R, 'email'>;
export type PhoneNumberFieldDescriptor<R extends boolean = boolean> =
  TextFieldDescriptor<R, 'phoneNumber'>;
export type SingleLineTextFieldDescriptor<R extends boolean = boolean> =
  TextFieldDescriptor<R, 'singleLineText'>;
export type LongTextFieldDescriptor<R extends boolean = boolean> =
  TextFieldDescriptor<R, 'longText'>;
export type ButtonFieldDescriptor<R extends boolean = boolean> =
  TextFieldDescriptor<R, 'button'>;
export type CurrencyFieldDescriptor<R extends boolean = boolean> =
  NumberFieldDescriptor<R, 'currency'>;
export type PercentFieldDescriptor<R extends boolean = boolean> =
  NumberFieldDescriptor<R, 'percent'>;
export type CountFieldDescriptor<R extends boolean = boolean> =
  NumberFieldDescriptor<R, 'count'>;
export type PositionFieldDescriptor<R extends boolean = boolean> =
  NumberFieldDescriptor<R, 'position'>;
export type RatingFieldDescriptor<R extends boolean = boolean> =
  NumberFieldDescriptor<R, 'rating'>;
export type DurationFieldDescriptor<R extends boolean = boolean> =
  NumberFieldDescriptor<R, 'duration'>;
export type CreatedAtFieldDescriptor = AutoDateFieldDescriptor<'createdAt'>;
export type UpdatedAtFieldDescriptor = AutoDateFieldDescriptor<'updatedAt'>;
export type ModifiedAtFieldDescriptor = AutoDateFieldDescriptor<'modifiedAt'>;
export type CollaboratorsFieldDescriptor<R extends boolean = boolean> =
  LinkFieldDescriptor<'collaborators', R, 'collaborators'>;
export type ModifiedByFieldDescriptor<R extends boolean = boolean> =
  LinkFieldDescriptor<'collaborators', R, 'modifiedBy'>;
export type CreatedByFieldDescriptor<R extends boolean = boolean> =
  LinkFieldDescriptor<'collaborators', R, 'createdBy'>;
export type FormulaFieldDescriptor<
  TReturnType extends ComputedReturnType = ComputedReturnType,
> = ComputedFieldDescriptor<'formula', TReturnType>;
export type LookupFieldDescriptor<
  TReturnType extends ComputedReturnType = ComputedReturnType,
> = ComputedFieldDescriptor<'lookup', TReturnType>;
export type RollupFieldDescriptor<
  TReturnType extends ComputedReturnType = ComputedReturnType,
> = ComputedFieldDescriptor<'rollup', TReturnType>;

export type TaylorFieldDescriptor =
  | TextFieldDescriptor
  | JsonFieldDescriptor
  | UrlFieldDescriptor
  | EmailFieldDescriptor
  | PhoneNumberFieldDescriptor
  | SingleLineTextFieldDescriptor
  | LongTextFieldDescriptor
  | ButtonFieldDescriptor
  | NumberFieldDescriptor
  | CurrencyFieldDescriptor
  | PercentFieldDescriptor
  | CountFieldDescriptor
  | PositionFieldDescriptor
  | RatingFieldDescriptor
  | DurationFieldDescriptor
  | CheckboxFieldDescriptor
  | DateFieldDescriptor
  | SearchFieldDescriptor
  | LinkFieldDescriptor
  | CollaboratorsFieldDescriptor
  | ModifiedByFieldDescriptor
  | CreatedByFieldDescriptor
  | AttachmentFieldDescriptor
  | SelectFieldDescriptor
  | AutoNumberFieldDescriptor
  | AutoDateFieldDescriptor
  | CreatedAtFieldDescriptor
  | UpdatedAtFieldDescriptor
  | ModifiedAtFieldDescriptor
  | FormulaFieldDescriptor
  | LookupFieldDescriptor
  | RollupFieldDescriptor;

export type TaylorTableSchema = Record<string, TaylorFieldDescriptor>;

export type TaylorRuntimeSchema = Record<string, TaylorTableSchema>;

export function defineTaylorSchema<const TSchema extends TaylorRuntimeSchema>(
  schema: TSchema,
): TSchema {
  return schema;
}

export function textField<const R extends boolean>({
  required,
}: RequiredOption<R>): TextFieldDescriptor<R> {
  return { type: 'text', required, insertable: true, updatable: true };
}

function textLikeField<const TType extends TextLikeFieldType, const R extends boolean>(
  type: TType,
  { required }: RequiredOption<R>,
): TextFieldDescriptor<R, TType> {
  return { type, required, insertable: true, updatable: true };
}

export function jsonField<const R extends boolean>(
  options: RequiredOption<R>,
): JsonFieldDescriptor<R> {
  return textLikeField('json', options);
}

export function urlField<const R extends boolean>(
  options: RequiredOption<R>,
): UrlFieldDescriptor<R> {
  return textLikeField('url', options);
}

export function emailField<const R extends boolean>(
  options: RequiredOption<R>,
): EmailFieldDescriptor<R> {
  return textLikeField('email', options);
}

export function phoneNumberField<const R extends boolean>(
  options: RequiredOption<R>,
): PhoneNumberFieldDescriptor<R> {
  return textLikeField('phoneNumber', options);
}

export function singleLineTextField<const R extends boolean>(
  options: RequiredOption<R>,
): SingleLineTextFieldDescriptor<R> {
  return textLikeField('singleLineText', options);
}

export function longTextField<const R extends boolean>(
  options: RequiredOption<R>,
): LongTextFieldDescriptor<R> {
  return textLikeField('longText', options);
}

export function buttonField<const R extends boolean>(
  options: RequiredOption<R>,
): ButtonFieldDescriptor<R> {
  return textLikeField('button', options);
}

export function numberField<const R extends boolean>({
  required,
}: RequiredOption<R>): NumberFieldDescriptor<R> {
  return { type: 'number', required, insertable: true, updatable: true };
}

function numberLikeField<
  const TType extends NumberLikeFieldType,
  const R extends boolean,
>(type: TType, { required }: RequiredOption<R>): NumberFieldDescriptor<R, TType> {
  return { type, required, insertable: true, updatable: true };
}

export function currencyField<const R extends boolean>(
  options: RequiredOption<R>,
): CurrencyFieldDescriptor<R> {
  return numberLikeField('currency', options);
}

export function percentField<const R extends boolean>(
  options: RequiredOption<R>,
): PercentFieldDescriptor<R> {
  return numberLikeField('percent', options);
}

export function countField<const R extends boolean>(
  options: RequiredOption<R>,
): CountFieldDescriptor<R> {
  return numberLikeField('count', options);
}

export function positionField<const R extends boolean>(
  options: RequiredOption<R>,
): PositionFieldDescriptor<R> {
  return numberLikeField('position', options);
}

export function ratingField<const R extends boolean>(
  options: RequiredOption<R>,
): RatingFieldDescriptor<R> {
  return numberLikeField('rating', options);
}

export function durationField<const R extends boolean>(
  options: RequiredOption<R>,
): DurationFieldDescriptor<R> {
  return numberLikeField('duration', options);
}

export function checkboxField<const R extends boolean>({
  required,
}: RequiredOption<R>): CheckboxFieldDescriptor<R> {
  return { type: 'checkbox', required, insertable: true, updatable: true };
}

export function dateField<const R extends boolean>({
  required,
}: RequiredOption<R>): DateFieldDescriptor<R> {
  return { type: 'date', required, insertable: true, updatable: true };
}

export function searchField(): SearchFieldDescriptor {
  return { type: 'search', required: false, insertable: true, updatable: true };
}

export function linkField<
  const TLinkedTo extends string,
  const R extends boolean,
>({
  required,
  linkedTo,
}: RequiredOption<R> & { linkedTo: TLinkedTo }): LinkFieldDescriptor<
  TLinkedTo,
  R
> {
  return {
    type: 'link',
    required,
    linkedTo,
    insertable: true,
    updatable: true,
  };
}

function collaboratorLinkField<
  const TType extends CollaboratorLinkFieldType,
  const R extends boolean,
>(type: TType, { required }: RequiredOption<R>): LinkFieldDescriptor<
  'collaborators',
  R,
  TType
> {
  return {
    type,
    required,
    linkedTo: 'collaborators',
    insertable: true,
    updatable: true,
  };
}

export function collaboratorsField<const R extends boolean>(
  options: RequiredOption<R>,
): CollaboratorsFieldDescriptor<R> {
  return collaboratorLinkField('collaborators', options);
}

export function modifiedByField<const R extends boolean>(
  options: RequiredOption<R>,
): ModifiedByFieldDescriptor<R> {
  return collaboratorLinkField('modifiedBy', options);
}

export function createdByField<const R extends boolean>(
  options: RequiredOption<R>,
): CreatedByFieldDescriptor<R> {
  return collaboratorLinkField('createdBy', options);
}

export function attachmentField<const R extends boolean>({
  required,
}: RequiredOption<R>): AttachmentFieldDescriptor<R> {
  return {
    type: 'attachment',
    required,
    linkedTo: 'attachmentTable',
    insertable: true,
    updatable: true,
  };
}

export function selectField<
  const TOptions extends readonly string[],
  const R extends boolean,
  const TMode extends 'single' | 'multi',
>({
  required,
  mode,
  options,
}: RequiredOption<R> & {
  mode: TMode;
  options: TOptions;
}): SelectFieldDescriptor<TOptions, R, TMode> {
  return {
    type: 'select',
    required,
    mode,
    options,
    insertable: true,
    updatable: true,
  };
}

export function autoNumberField(): AutoNumberFieldDescriptor {
  return {
    type: 'autoNumber',
    required: false,
    insertable: false,
    updatable: false,
  };
}

export function autoDateField(): AutoDateFieldDescriptor {
  return {
    type: 'autoDate',
    required: false,
    insertable: false,
    updatable: false,
  };
}

function systemDateField<const TType extends SystemDateFieldType>(
  type: TType,
): AutoDateFieldDescriptor<TType> {
  return {
    type,
    required: false,
    insertable: false,
    updatable: false,
  };
}

export function createdAtField(): CreatedAtFieldDescriptor {
  return systemDateField('createdAt');
}

export function updatedAtField(): UpdatedAtFieldDescriptor {
  return systemDateField('updatedAt');
}

export function modifiedAtField(): ModifiedAtFieldDescriptor {
  return systemDateField('modifiedAt');
}

function computedField<
  const TType extends ComputedFieldType,
  const TReturnType extends ComputedReturnType,
>(type: TType, returnType: TReturnType): ComputedFieldDescriptor<TType, TReturnType> {
  return {
    type,
    returnType,
    required: false,
    insertable: false,
    updatable: false,
  };
}

export function formulaField<const TReturnType extends ComputedReturnType>({
  returnType,
}: {
  returnType: TReturnType;
}): FormulaFieldDescriptor<TReturnType> {
  return computedField('formula', returnType);
}

export function lookupField<const TReturnType extends ComputedReturnType>({
  returnType,
}: {
  returnType: TReturnType;
}): LookupFieldDescriptor<TReturnType> {
  return computedField('lookup', returnType);
}

export function rollupField<const TReturnType extends ComputedReturnType>({
  returnType,
}: {
  returnType: TReturnType;
}): RollupFieldDescriptor<TReturnType> {
  return computedField('rollup', returnType);
}

type ReadonlyColumn<TColumn extends ColumnType<any, any, any, false, any, any>> =
  ColumnType<
    TColumn['raw'],
    never,
    never,
    false,
    TColumn['filters'],
    TColumn['aggregations']
  >;

type InferComputedField<TReturnType extends ComputedReturnType> =
  TReturnType extends 'number'
    ? AutoGeneratedNumberColumnType
    : TReturnType extends 'boolean'
      ? ReadonlyColumn<CheckboxColumnType<false>>
      : TReturnType extends 'date'
        ? AutoGeneratedDateColumnType
        : ReadonlyColumn<TextColumnType<false>>;

export type InferTaylorField<TField extends TaylorFieldDescriptor> =
  TField extends TextFieldDescriptor<infer R, TextLikeFieldType>
    ? TextColumnType<R>
    : TField extends NumberFieldDescriptor<infer R, NumberLikeFieldType>
      ? NumberColumnType<R>
      : TField extends CheckboxFieldDescriptor<infer R>
        ? CheckboxColumnType<R>
        : TField extends DateFieldDescriptor<infer R>
          ? DateColumnType<R>
          : TField extends SearchFieldDescriptor
            ? SearchColumnType<false>
            : TField extends LinkFieldDescriptor<
                  infer TLinkedTo,
                  infer R,
                  'link' | CollaboratorLinkFieldType
                >
              ? LinkColumnType<TLinkedTo, R>
              : TField extends AttachmentFieldDescriptor<infer R>
                ? AttachmentColumnType<R>
                : TField extends SelectFieldDescriptor<
                      infer TOptions,
                      infer R,
                      infer TMode
                    >
                  ? TMode extends 'single'
                    ? SingleSelectColumnType<TOptions, R>
                    : MultiSelectColumnType<TOptions, R>
                  : TField extends AutoNumberFieldDescriptor
                    ? AutoGeneratedNumberColumnType
                    : TField extends AutoDateFieldDescriptor<SystemDateFieldType>
                      ? AutoGeneratedDateColumnType
                      : TField extends ComputedFieldDescriptor<
                            ComputedFieldType,
                            infer TReturnType
                          >
                        ? InferComputedField<TReturnType>
                        : never;

export type InferTaylorTable<TTableSchema extends TaylorTableSchema> = {
  [K in keyof TTableSchema]: InferTaylorField<TTableSchema[K]>;
};

export type InferTaylorDatabase<TSchema extends TaylorRuntimeSchema> = {
  [K in keyof TSchema]: InferTaylorTable<TSchema[K]>;
};
