import {
  AttachmentColumnType,
  AutoGeneratedDateColumnType,
  AutoGeneratedNumberColumnType,
  CheckboxColumnType,
  DateColumnType,
  LinkColumnType,
  MultiSelectColumnType,
  NumberColumnType,
  SearchColumnType,
  SingleSelectColumnType,
  TextColumnType,
} from './column-types.js';

type RequiredOption<R extends boolean = boolean> = {
  required: R;
};

type BaseFieldDescriptor<
  TType extends string,
  R extends boolean,
  TInsertable extends boolean,
  TUpdatable extends boolean,
> = {
  type: TType;
  required: R;
  insertable: TInsertable;
  updatable: TUpdatable;
};

export type TextFieldDescriptor<R extends boolean = boolean> =
  BaseFieldDescriptor<'text', R, true, true>;

export type NumberFieldDescriptor<R extends boolean = boolean> =
  BaseFieldDescriptor<'number', R, true, true>;

export type CheckboxFieldDescriptor<R extends boolean = boolean> =
  BaseFieldDescriptor<'checkbox', R, true, true>;

export type DateFieldDescriptor<R extends boolean = boolean> =
  BaseFieldDescriptor<'date', R, true, true>;

export type SearchFieldDescriptor = BaseFieldDescriptor<
  'search',
  false,
  true,
  true
>;

export type LinkFieldDescriptor<
  TLinkedTo extends string = string,
  R extends boolean = boolean,
> = BaseFieldDescriptor<'link', R, true, true> & {
  linkedTo: TLinkedTo;
};

export type AttachmentFieldDescriptor<R extends boolean = boolean> =
  BaseFieldDescriptor<'attachment', R, true, true> & {
    linkedTo: 'attachmentTable';
  };

export type SelectFieldDescriptor<
  TOptions extends readonly string[] = readonly string[],
  R extends boolean = boolean,
  TMode extends 'single' | 'multi' = 'single' | 'multi',
> = BaseFieldDescriptor<'select', R, true, true> & {
  mode: TMode;
  options: TOptions;
};

export type AutoNumberFieldDescriptor = BaseFieldDescriptor<
  'autoNumber',
  false,
  false,
  false
>;

export type AutoDateFieldDescriptor = BaseFieldDescriptor<
  'autoDate',
  false,
  false,
  false
>;

export type TaylorFieldDescriptor =
  | TextFieldDescriptor
  | NumberFieldDescriptor
  | CheckboxFieldDescriptor
  | DateFieldDescriptor
  | SearchFieldDescriptor
  | LinkFieldDescriptor
  | AttachmentFieldDescriptor
  | SelectFieldDescriptor
  | AutoNumberFieldDescriptor
  | AutoDateFieldDescriptor;

export type TaylorTableSchema = Record<string, TaylorFieldDescriptor>;

export type TaylorRuntimeSchema = Record<string, TaylorTableSchema>;

export function defineTaylorSchema<const TSchema extends TaylorRuntimeSchema>(
  schema: TSchema,
): TSchema {
  return schema;
}

export function textField<const R extends boolean>({
  required,
}: RequiredOption<R>): TextFieldDescriptor<R> {
  return { type: 'text', required, insertable: true, updatable: true };
}

export function numberField<const R extends boolean>({
  required,
}: RequiredOption<R>): NumberFieldDescriptor<R> {
  return { type: 'number', required, insertable: true, updatable: true };
}

export function checkboxField<const R extends boolean>({
  required,
}: RequiredOption<R>): CheckboxFieldDescriptor<R> {
  return { type: 'checkbox', required, insertable: true, updatable: true };
}

export function dateField<const R extends boolean>({
  required,
}: RequiredOption<R>): DateFieldDescriptor<R> {
  return { type: 'date', required, insertable: true, updatable: true };
}

export function searchField(): SearchFieldDescriptor {
  return { type: 'search', required: false, insertable: true, updatable: true };
}

export function linkField<
  const TLinkedTo extends string,
  const R extends boolean,
>({
  required,
  linkedTo,
}: RequiredOption<R> & { linkedTo: TLinkedTo }): LinkFieldDescriptor<
  TLinkedTo,
  R
> {
  return {
    type: 'link',
    required,
    linkedTo,
    insertable: true,
    updatable: true,
  };
}

export function attachmentField<const R extends boolean>({
  required,
}: RequiredOption<R>): AttachmentFieldDescriptor<R> {
  return {
    type: 'attachment',
    required,
    linkedTo: 'attachmentTable',
    insertable: true,
    updatable: true,
  };
}

export function selectField<
  const TOptions extends readonly string[],
  const R extends boolean,
  const TMode extends 'single' | 'multi',
>({
  required,
  mode,
  options,
}: RequiredOption<R> & {
  mode: TMode;
  options: TOptions;
}): SelectFieldDescriptor<TOptions, R, TMode> {
  return {
    type: 'select',
    required,
    mode,
    options,
    insertable: true,
    updatable: true,
  };
}

export function autoNumberField(): AutoNumberFieldDescriptor {
  return {
    type: 'autoNumber',
    required: false,
    insertable: false,
    updatable: false,
  };
}

export function autoDateField(): AutoDateFieldDescriptor {
  return {
    type: 'autoDate',
    required: false,
    insertable: false,
    updatable: false,
  };
}

export type InferTaylorField<TField extends TaylorFieldDescriptor> =
  TField extends TextFieldDescriptor<infer R>
    ? TextColumnType<R>
    : TField extends NumberFieldDescriptor<infer R>
      ? NumberColumnType<R>
      : TField extends CheckboxFieldDescriptor<infer R>
        ? CheckboxColumnType<R>
        : TField extends DateFieldDescriptor<infer R>
          ? DateColumnType<R>
          : TField extends SearchFieldDescriptor
            ? SearchColumnType<false>
            : TField extends LinkFieldDescriptor<infer TLinkedTo, infer R>
              ? LinkColumnType<TLinkedTo, R>
              : TField extends AttachmentFieldDescriptor<infer R>
                ? AttachmentColumnType<R>
                : TField extends SelectFieldDescriptor<
                      infer TOptions,
                      infer R,
                      infer TMode
                    >
                  ? TMode extends 'single'
                    ? SingleSelectColumnType<TOptions, R>
                    : MultiSelectColumnType<TOptions, R>
                  : TField extends AutoNumberFieldDescriptor
                    ? AutoGeneratedNumberColumnType
                    : TField extends AutoDateFieldDescriptor
                      ? AutoGeneratedDateColumnType
                      : never;

export type InferTaylorTable<TTableSchema extends TaylorTableSchema> = {
  [K in keyof TTableSchema]: InferTaylorField<TTableSchema[K]>;
};

export type InferTaylorDatabase<TSchema extends TaylorRuntimeSchema> = {
  [K in keyof TSchema]: InferTaylorTable<TSchema[K]>;
};
