import {
  Attachment,
  AttachmentColumnType,
  AutoGeneratedNumberColumnType,
  DateColumnType,
  LinkColumnType,
  NumberColumnType,
  SingleSelectColumnType,
  MultiSelectColumnType,
  TextColumnType,
  SearchColumnType,
} from '@taylordb/shared';
import {
  attachmentField,
  autoNumberField,
  buttonField,
  checkboxField,
  collaboratorsField,
  countField,
  createdAtField,
  createdByField,
  currencyField,
  dateField,
  defineTaylorSchema,
  durationField,
  emailField,
  exposingFieldTypes,
  formulaField,
  jsonField,
  linkField,
  longTextField,
  lookupField,
  modifiedAtField,
  modifiedByField,
  numberField,
  percentField,
  phoneNumberField,
  positionField,
  ratingField,
  rollupField,
  searchField,
  selectField,
  singleLineTextField,
  textField,
  createQueryBuilder,
  sum,
  updatedAtField,
  urlField,
} from '../index.js';
import type {
  Aggregates,
  BambooFieldsType,
  ColumnNames,
  FieldWithDirection,
  Filters,
  FiltersSet,
  InferTaylorDatabase,
  InferActionInput,
  InferActionResult,
  Insertable,
  LinkColumnNames,
  LimitOffset,
  NonLinkColumnNames,
  Updatable,
} from '../index.js';
import { SocketConnection } from '../socket-connection.js';
import { TaylorDatabase as TaylorDatabaseOriginal } from './taylorclient.types.js';

export const CustomersStatusOptions = ['Pending', 'Active'] as const;
export const TagsOptions = ['Urgent', 'Low Priority'] as const;

interface OrdersTable {
  id: AutoGeneratedNumberColumnType;
  createdAt: DateColumnType<false>;
  updatedAt: DateColumnType<false>;
  amount: NumberColumnType<false>;
  customer: LinkColumnType<'customers', false>;
  status: SingleSelectColumnType<typeof CustomersStatusOptions, false>;
  tags: MultiSelectColumnType<typeof TagsOptions, false>;
}

interface CustomersTable {
  id: AutoGeneratedNumberColumnType;
  createdAt: DateColumnType<false>;
  updatedAt: DateColumnType<false>;
  searchText: SearchColumnType<false>;
  firstName: TextColumnType<true>;
  lastName: TextColumnType<false>;
  avatar: AttachmentColumnType<false>;
  orders: LinkColumnType<'orders', false>;
}

interface TaylorDatabase extends TaylorDatabaseOriginal {
  orders: OrdersTable;
  customers: CustomersTable;
  _plugins: {
    email: {
      send: {
        input: { recordId?: number; scheduledAt?: string };
        result: { success: boolean; data?: any };
      };
      archive: {
        input: Record<string, any>;
        result: any;
      };
    };
  };
}

jest.mock('socket.io-client', () => {
  const mockSocket = {
    on: jest.fn(),
    emit: jest.fn(),
    once: jest.fn(),
  };
  return {
    io: jest.fn(() => mockSocket),
  };
});

describe('runtime schema helpers', () => {
  it('exports existing query-builder input and metadata types', () => {
    const createPayload = {
      firstName: 'Jane',
      lastName: 'Doe',
      orders: [1],
    } satisfies Insertable<TaylorDatabase['customers']>;

    const missingRequiredCreate =
      // @ts-expect-error required create fields must be present
      { lastName: 'Doe' } satisfies Insertable<TaylorDatabase['customers']>;

    const nonInsertableCreateField = {
      firstName: 'Jane',
      // @ts-expect-error non-insertable fields must not be accepted
      id: 1,
    } satisfies Insertable<TaylorDatabase['customers']>;

    const updatePayload = {
      firstName: 'Janet',
      orders: { newIds: [1], deletedIds: [] },
    } satisfies Updatable<TaylorDatabase['customers']>;

    const nonUpdatableUpdateField = {
      // @ts-expect-error non-updatable fields must not be accepted
      id: 1,
    } satisfies Updatable<TaylorDatabase['customers']>;

    const textFilter = {
      field: 'firstName',
      operator: 'contains',
      value: 'Jan',
    } satisfies Filters<ColumnNames<TaylorDatabase['customers']> & string>;

    const omittedValueFilter = {
      field: 'lastName',
      operator: 'isEmpty',
    } satisfies Filters<ColumnNames<TaylorDatabase['customers']> & string>;

    const filtersSet = {
      conjunction: 'and',
      filtersSet: [
        textFilter,
        {
          conjunction: 'or',
          filtersSet: [omittedValueFilter],
        },
      ],
    } satisfies FiltersSet<ColumnNames<TaylorDatabase['customers']> & string>;

    const orderBy = {
      field: 'lastName',
      direction: 'asc',
    } satisfies FieldWithDirection<
      ColumnNames<TaylorDatabase['customers']> & string
    >;

    const pagination = {
      limit: 10,
      offset: 20,
    } satisfies LimitOffset;

    const columnField: ColumnNames<TaylorDatabase['customers']> = 'orders';
    const selectFieldName: NonLinkColumnNames<TaylorDatabase['customers']> =
      'firstName';
    const linkFieldName: LinkColumnNames<TaylorDatabase['customers']> =
      'orders';

    // @ts-expect-error link fields are not selectable scalar fields
    const invalidSelectField: NonLinkColumnNames<TaylorDatabase['customers']> =
      'orders';

    const aggregates = {
      amount: {
        sum: 100,
      },
    } satisfies Aggregates<
      TaylorDatabase,
      'orders',
      { amount: readonly ['sum'] }
    >;

    const pluginInput = {
      recordId: 1,
    } satisfies InferActionInput<TaylorDatabase, 'email', 'send'>;

    const pluginResult = {
      success: true,
    } satisfies InferActionResult<TaylorDatabase, 'email', 'send'>;

    void createPayload;
    void missingRequiredCreate;
    void nonInsertableCreateField;
    void updatePayload;
    void nonUpdatableUpdateField;
    void filtersSet;
    void orderBy;
    void pagination;
    void columnField;
    void selectFieldName;
    void linkFieldName;
    void invalidSelectField;
    void aggregates;
    void pluginInput;
    void pluginResult;
  });

  it('preserves Bamboo field-specific runtime helpers and inference', () => {
    const fieldTypes = exposingFieldTypes satisfies readonly BambooFieldsType[];
    expect(fieldTypes).toContain('currency');
    expect(fieldTypes).toContain('modifiedBy');
    expect(fieldTypes).toContain('rollup');

    const schema = defineTaylorSchema({
      allFields: {
        json: jsonField({ required: false }),
        number: numberField({ required: false }),
        date: dateField({ required: false }),
        modifiedAt: modifiedAtField(),
        link: linkField({ required: false, linkedTo: 'linked' }),
        currency: currencyField({ required: false }),
        percent: percentField({ required: false }),
        url: urlField({ required: false }),
        email: emailField({ required: false }),
        phoneNumber: phoneNumberField({ required: false }),
        checkbox: checkboxField({ required: false }),
        select: selectField({
          required: false,
          mode: 'single',
          options: ['One', 'Two'] as const,
        }),
        count: countField({ required: false }),
        autoNumber: autoNumberField(),
        formula: formulaField({ returnType: 'number' }),
        position: positionField({ required: false }),
        rating: ratingField({ required: false }),
        createdAt: createdAtField(),
        updatedAt: updatedAtField(),
        singleLineText: singleLineTextField({ required: false }),
        text: textField({ required: false }),
        longText: longTextField({ required: false }),
        lookup: lookupField({ returnType: 'json' }),
        rollup: rollupField({ returnType: 'date' }),
        collaborators: collaboratorsField({ required: false }),
        modifiedBy: modifiedByField({ required: false }),
        duration: durationField({ required: false }),
        createdBy: createdByField({ required: false }),
        attachment: attachmentField({ required: false }),
        button: buttonField({ required: false }),
      },
      linked: {
        id: autoNumberField(),
      },
    });

    type FieldDatabase = InferTaylorDatabase<typeof schema>;

    expect(schema.allFields.currency.type).toBe('currency');
    expect(schema.allFields.modifiedAt.type).toBe('modifiedAt');
    expect(schema.allFields.formula).toMatchObject({
      type: 'formula',
      returnType: 'number',
      insertable: false,
      updatable: false,
    });
    expect(schema.allFields.lookup.type).toBe('lookup');
    expect(schema.allFields.rollup.type).toBe('rollup');
    expect(schema.allFields.modifiedBy.linkedTo).toBe('collaborators');

    const insertable = {
      json: '{}',
      number: 1,
      date: '2026-06-22',
      link: [1],
      currency: 10,
      percent: 50,
      url: 'https://example.com',
      email: 'hello@example.com',
      phoneNumber: '+15555555555',
      checkbox: true,
      select: 'One',
      count: 1,
      position: 1,
      rating: 5,
      singleLineText: 'single',
      text: 'text',
      longText: 'long',
      collaborators: [1],
      modifiedBy: [1],
      duration: 60,
      createdBy: [1],
      attachment: [],
      button: 'run',
    } satisfies Insertable<FieldDatabase['allFields']>;

    const updatable = {
      currency: 20,
      modifiedBy: { newIds: [1], deletedIds: [] },
    } satisfies Updatable<FieldDatabase['allFields']>;

    const invalidSystemInsert = {
      // @ts-expect-error system dates must not be insertable
      createdAt: '2026-06-22',
    } satisfies Insertable<FieldDatabase['allFields']>;

    const invalidComputedInsert = {
      // @ts-expect-error computed fields must not be insertable
      formula: 1,
    } satisfies Insertable<FieldDatabase['allFields']>;

    void insertable;
    void updatable;
    void invalidSystemInsert;
    void invalidComputedInsert;
  });

  it('preserves runtime field metadata and infers query-builder types', () => {
    const runtimeSchema = defineTaylorSchema({
      projects: {
        id: autoNumberField(),
        name: textField({ required: true }),
        budget: numberField({ required: false }),
        status: selectField({
          required: false,
          mode: 'single',
          options: ['Pending', 'Active'] as const,
        }),
        tags: selectField({
          required: false,
          mode: 'multi',
          options: ['Urgent', 'Low Priority'] as const,
        }),
        owner: linkField({ required: false, linkedTo: 'collaborators' }),
        createdAt: dateField({ required: false }),
        searchText: searchField(),
      },
      collaborators: {
        id: autoNumberField(),
        name: textField({ required: true }),
      },
    });

    type RuntimeSchemaDatabase = InferTaylorDatabase<typeof runtimeSchema>;

    expect(runtimeSchema.projects.status).toEqual({
      type: 'select',
      required: false,
      mode: 'single',
      options: ['Pending', 'Active'],
      insertable: true,
      updatable: true,
    });
    expect(runtimeSchema.projects.owner).toMatchObject({
      type: 'link',
      required: false,
      linkedTo: 'collaborators',
      insertable: true,
      updatable: true,
    });
    expect(runtimeSchema.projects.id).toMatchObject({
      type: 'autoNumber',
      insertable: false,
      updatable: false,
    });

    const qb = createQueryBuilder<RuntimeSchemaDatabase>({
      baseUrl: 'http://localhost',
      baseId: 'test-base-id',
      apiKey: 'test',
    });

    qb.selectFrom('projects')
      .select(['name', 'status'])
      .where('status', '=', 'Active')
      .where('tags', 'hasAnyOf', ['Urgent'])
      .where('owner', '=', 1)
      .where('budget', '>=', 100);

    qb.selectFrom('projects').with({
      owner: owner => owner.select(['id', 'name']),
    });

    // @ts-expect-error with object form must include at least one relation
    qb.selectFrom('projects').with({});

    qb.selectFrom('projects').with({
      // @ts-expect-error unknown relation keys must be rejected
      unknown: owner => owner.select(['id']),
    });

    qb.selectFrom('projects').with({
      // @ts-expect-error non-link fields must not be accepted as relations
      name: project => project.select(['id']),
    });

    qb.selectFrom('projects').with({
      owner: owner =>
        // @ts-expect-error relation callbacks must be scoped to the linked table
        owner.select(['budget']),
    });

    qb.insertInto('projects').values({
      name: 'Runtime schema',
      status: 'Pending',
      tags: ['Low Priority'],
      owner: [1],
      budget: 10,
      createdAt: '2026-05-19',
      searchText: 'runtime schema',
    });

    qb.update('projects').set({
      status: 'Active',
      tags: ['Urgent'],
      owner: { newIds: [1], deletedIds: [] },
    });
  });

  it('keeps generated plugin action types strict', () => {
    const qb = createQueryBuilder<TaylorDatabase>({
      baseUrl: 'http://localhost',
      baseId: 'test-base-id',
      apiKey: 'test',
    });

    qb.plugin('email').action('send').input({
      recordId: 1,
      scheduledAt: '2026-05-19T00:00:00Z',
    });

    // @ts-expect-error unknown plugins must be rejected
    qb.plugin('not-a-plugin');

    // @ts-expect-error unknown actions must be rejected
    qb.plugin('email').action('not-an-action');

    // @ts-expect-error input must match the action input type
    qb.plugin('email').action('send').input({ recordId: 'wrong' });

    // @ts-expect-error excess input fields must be rejected
    qb.plugin('email').action('send').input({ unknown: true });
  });

  it('does not expose plugins as queryable tables', () => {
    const qb = createQueryBuilder<TaylorDatabase>({
      baseUrl: 'http://localhost',
      baseId: 'test-base-id',
      apiKey: 'test',
    });

    // @ts-expect-error plugin metadata is not a readable table
    qb.selectFrom('_plugins');

    // @ts-expect-error plugin metadata is not an insertable table
    qb.insertInto('_plugins');

    // @ts-expect-error plugin metadata is not an updatable table
    qb.update('_plugins');

    // @ts-expect-error plugin metadata is not a deletable table
    qb.deleteFrom('_plugins');

    // @ts-expect-error plugin metadata is not an aggregatable table
    qb.aggregateFrom('_plugins');
  });
});

describe('QueryBuilder', () => {
  let mockRawRequest: jest.Mock;

  beforeEach(() => {
    mockRawRequest = jest.fn().mockResolvedValue({ execute: [] });
    SocketConnection.prototype.rawRequest = mockRawRequest;
    SocketConnection.prototype.getCurrentUserId = jest
      .fn()
      .mockResolvedValue('test-user-id');
  });

  // @ts-ignore
  const qb = createQueryBuilder<TaylorDatabase>({
    baseUrl: 'http://localhost',
    baseId: 'test-base-id',
    apiKey: 'test',
  });

  it('should compile a select query and execute', async () => {
    await qb
      .selectFrom('customers')
      .select(['firstName', 'lastName'])
      .where('firstName', '=', 'John')
      .orderBy('lastName', 'asc')
      .paginate(1, 10)
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'customers',
      fields: ['firstName', 'lastName'],
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'firstName',
            operator: '=',
            value: 'John',
          },
        ],
      },
      sorting: [{ field: 'lastName', direction: 'asc' }],
      pagination: { offset: 0, limit: 10 },
    });
  });

  it('should not include pagination property if not used', async () => {
    await qb
      .selectFrom('customers')
      .select(['firstName'])
      .where('firstName', '=', 'John')
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).not.toHaveProperty('pagination');
  });

  it('should apply limit to a select query', async () => {
    await qb.selectFrom('customers').select(['firstName']).limit(5).execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'customers',
      fields: ['firstName'],
      pagination: { limit: 5 },
    });
  });

  it('should apply offset to a select query', async () => {
    await qb.selectFrom('customers').select(['firstName']).offset(10).execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'customers',
      fields: ['firstName'],
      pagination: { offset: 10 },
    });
  });

  it('should apply limit and offset to a select query', async () => {
    await qb
      .selectFrom('customers')
      .select(['firstName'])
      .limit(5)
      .offset(10)
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'customers',
      fields: ['firstName'],
      pagination: { limit: 5, offset: 10 },
    });
  });

  it('should apply pagination with a different page', async () => {
    await qb
      .selectFrom('customers')
      .select(['firstName'])
      .paginate(3, 15)
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'customers',
      fields: ['firstName'],
      pagination: { limit: 15, offset: 30 },
    });
  });

  it('should count the records', async () => {
    mockRawRequest.mockResolvedValue([{ total: 123 }]);
    const count = await qb
      .selectFrom('customers')
      .where('firstName', '=', 'John')
      .count();

    expect(count).toBe(123);
    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'pagination',
      tableName: 'customers',
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'firstName',
            operator: '=',
            value: 'John',
          },
        ],
      },
    });
  });

  it('should compile an insert query and execute', async () => {
    await qb
      .insertInto('customers')
      .values({
        firstName: 'Jane',
        lastName: 'Doe',
      })
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'create',
      tableName: 'customers',
      createdRecords: [{ firstName: 'Jane', lastName: 'Doe' }],
    });
  });

  it('should compile an update query and execute', async () => {
    await qb
      .update('customers')
      .set({ lastName: 'Smith' })
      .where('id', '=', 1)
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'update',
      tableName: 'customers',
      values: { lastName: 'Smith' },
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'id',
            operator: '=',
            value: 1,
          },
        ],
      },
    });
  });

  it('should compile a delete query and execute', async () => {
    await qb.deleteFrom('customers').where('id', '=', 1).execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'delete',
      tableName: 'customers',
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'id',
            operator: '=',
            value: 1,
          },
        ],
      },
    });
  });

  it('should compile a batch query and execute', async () => {
    await qb
      .batch([
        qb.selectFrom('customers').select(['firstName', 'lastName']),
        qb
          .insertInto('customers')
          .values({ firstName: 'John', lastName: 'Doe' }),
      ])
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata).toHaveLength(2);
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'customers',
    });
    expect(variables.metadata[1]).toMatchObject({
      type: 'create',
      tableName: 'customers',
    });
  });

  it('should compile a metrics query and flatten results', async () => {
    // Mock response with nested structure (rawRequest extracts execute key, so return array directly)
    const mockNestedResponse = [
      [
        {
          slug: 'firstName',
          value: 'John',
          count: 2,
          aggregates: {
            id: { sum: 100 },
          },
          children: [
            {
              slug: 'lastName',
              value: 'Doe',
              count: 1,
              aggregates: {
                id: { sum: 50 },
              },
            },
          ],
        },
      ],
    ];

    // Mock to return the array directly (as rawRequest would after extracting from { execute: [...] })
    mockRawRequest.mockResolvedValueOnce(mockNestedResponse);

    const result = await qb
      .aggregateFrom('customers')
      .groupBy('firstName', 'asc')
      .groupBy('lastName', 'desc')
      .metrics({
        idSum: sum('id'),
      })
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'aggregation',
      tableName: 'customers',
      groupings: [
        { field: 'firstName', direction: 'asc' },
        { field: 'lastName', direction: 'desc' },
      ],
      aggregations: {
        id: ['sum'],
      },
    });

    // Verify flattened result
    expect(result).toEqual([
      {
        firstName: 'John',
        lastName: 'Doe',
        idSum: 50,
      },
    ]);
  });

  it('should flatten metrics results without groupBy', async () => {
    // Mock response with no groupBy (flat structure)
    // rawRequest extracts execute key, so return array directly
    const mockFlatResponse = [
      [
        {
          count: 10,
          aggregates: {
            id: { sum: 500 },
          },
        },
      ],
    ];

    mockRawRequest.mockResolvedValueOnce(mockFlatResponse);

    const result = await qb
      .aggregateFrom('customers')
      .metrics({
        idSum: sum('id'),
      })
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'aggregation',
      tableName: 'customers',
      aggregations: {
        id: ['sum'],
      },
    });

    // Verify flattened result (no groupBy fields)
    expect(result).toEqual([
      {
        idSum: 500,
      },
    ]);
  });

  it('should compile a cross-table query and execute', async () => {
    await qb
      .selectFrom('customers')
      .where('orders', 'hasAnyOf', qb => qb.where('amount', '>', 100))
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'customers',
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'orders',
            operator: 'hasAnyOf',
            value: [
              'cross-table',
              {
                conjunction: 'and',
                filtersSet: [
                  {
                    field: 'amount',
                    operator: '>',
                    value: 100,
                  },
                ],
              },
            ],
          },
        ],
      },
    });
  });

  it('should handle a successful transaction', async () => {
    const mockRawRequest = jest
      .fn()
      .mockResolvedValueOnce({
        startTransaction: 'test-transaction-id',
      })
      .mockResolvedValueOnce({ execute: [] })
      .mockResolvedValueOnce({ commitTransaction: true });

    SocketConnection.prototype.rawRequest = mockRawRequest;

    // @ts-ignore
    const qb = createQueryBuilder<TaylorDatabase>({
      baseUrl: 'http://localhost',
      baseId: 'test-base-id',
      apiKey: 'test',
    });

    await qb.transaction(txQb => {
      return txQb
        .insertInto('customers')
        .values({ firstName: 'John', lastName: 'Doe' })
        .execute();
    });

    expect(mockRawRequest).toHaveBeenCalledTimes(3);

    const startTransactionCall = mockRawRequest.mock.calls[0];
    expect(startTransactionCall[0]).toContain('startTransaction');

    const executeCall = mockRawRequest.mock.calls[1];
    expect(executeCall[3]).toBe('test-transaction-id');

    const commitTransactionCall = mockRawRequest.mock.calls[2];
    expect(commitTransactionCall[0]).toContain('commitTransaction');
    expect(commitTransactionCall[3]).toBe('test-transaction-id');
  });

  it('should handle a failed transaction and rollback', async () => {
    const transactionId = 'test-transaction-id-fail';
    const errorMessage = 'Something went wrong';

    const mockRawRequest = jest
      .fn()
      .mockResolvedValueOnce({ startTransaction: transactionId })
      .mockRejectedValueOnce(new Error(errorMessage))
      .mockResolvedValueOnce({ rollbackTransaction: true });

    SocketConnection.prototype.rawRequest = mockRawRequest;

    // @ts-ignore
    const qb = createQueryBuilder<TaylorDatabase>({
      baseUrl: 'http://localhost',
      baseId: 'test-base-id',
      apiKey: 'test',
    });

    await expect(
      qb.transaction(txQb => {
        return txQb
          .insertInto('customers')
          .values({ firstName: 'John', lastName: 'Doe' })
          .execute();
      }),
    ).rejects.toThrow(errorMessage);

    expect(mockRawRequest).toHaveBeenCalledTimes(3);

    const startTransactionCall = mockRawRequest.mock.calls[0];
    expect(startTransactionCall[0]).toContain('startTransaction');

    const executeCall = mockRawRequest.mock.calls[1];
    expect(executeCall[3]).toBe(transactionId);

    const rollbackTransactionCall = mockRawRequest.mock.calls[2];
    expect(rollbackTransactionCall[0]).toContain('rollbackTransaction');
    expect(rollbackTransactionCall[3]).toBe(transactionId);
  });

  it('should not have transaction method within a transaction', async () => {
    const mockRawRequest = jest
      .fn()
      .mockResolvedValueOnce({
        startTransaction: 'test-transaction-id-no-nested',
      })
      .mockResolvedValueOnce({ commitTransaction: true });

    SocketConnection.prototype.rawRequest = mockRawRequest;

    // @ts-ignore
    const qb = createQueryBuilder<TaylorDatabase>({
      baseUrl: 'http://localhost',
      baseId: 'test-base-id',
      apiKey: 'test',
    });

    await qb.transaction(async txQb => {
      expect(txQb).not.toHaveProperty('transaction');
    });

    expect(mockRawRequest).toHaveBeenCalledTimes(2);
  });

  it('should compile an insert query with a number array for a link field', async () => {
    await qb
      .insertInto('customers')
      .values({
        firstName: 'Jane',
        lastName: 'Doe',
        orders: [1, 2, 3],
      })
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'create',
      tableName: 'customers',
      createdRecords: [
        {
          firstName: 'Jane',
          lastName: 'Doe',
          orders: [1, 2, 3],
        },
      ],
    });
  });

  it('should compile an update query with a number array for a link field', async () => {
    await qb
      .update('customers')
      .set({
        lastName: 'Smith',
        orders: [1, 2, 3],
      })
      .where('id', '=', 1)
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'update',
      tableName: 'customers',
      values: {
        lastName: 'Smith',
        orders: [1, 2, 3],
      },
    });
  });

  it('should compile an insert query with attachments and execute', async () => {
    // Mock uploadAttachments to return a mock Attachment
    const mockAttachment = new Attachment({
      collectionName: 'string',
      fileInformation: {
        path: 'test-path.png',
        mimetype: 'image/png',
        size: 12345,
      },
    } as any);
    // @ts-ignore
    qb.uploadAttachments = jest.fn().mockResolvedValue([mockAttachment]);

    await qb
      .insertInto('customers')
      .values({
        firstName: 'Jane',
        lastName: 'Doe',
        avatar: await qb.uploadAttachments([
          { file: new Blob(['']), name: 'test.png' },
        ]),
      })
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'create',
      tableName: 'customers',
      createdRecords: [
        {
          firstName: 'Jane',
          lastName: 'Doe',
          avatar: [
            {
              url: 'test-path.png',
              fileType: 'image/png',
              size: 12345,
            },
          ],
        },
      ],
    });
  });

  it('should compile an update query with attachments and execute', async () => {
    // Mock uploadAttachments to return a mock Attachment
    const mockAttachment = new Attachment({
      collectionName: 'string',
      fileInformation: {
        path: 'test-path.png',
        mimetype: 'image/png',
        size: 12345,
      },
    } as any);
    // @ts-ignore
    qb.uploadAttachments = jest.fn().mockResolvedValue([mockAttachment]);

    await qb
      .update('customers')
      .set({
        lastName: 'Smith',
        avatar: await qb.uploadAttachments([
          { file: new Blob(['']), name: 'test.png' },
        ]),
      })
      .where('id', '=', 1)
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'update',
      tableName: 'customers',
      values: {
        lastName: 'Smith',
        avatar: [
          {
            url: 'test-path.png',
            fileType: 'image/png',
            size: 12345,
          },
        ],
      },
    });
  });

  it('should compile an attachment update with newAttachments and deletedUrls', async () => {
    const mockAttachment = new Attachment({
      collectionName: 'string',
      fileInformation: {
        path: 'test-path.png',
        mimetype: 'image/png',
        size: 12345,
      },
    } as any);
    // @ts-ignore
    qb.uploadAttachments = jest.fn().mockResolvedValue([mockAttachment]);

    await qb
      .update('customers')
      .set({
        avatar: {
          newAttachments: await qb.uploadAttachments([
            { file: new Blob(['']), name: 'test.png' },
          ]),
          deletedUrls: ['https://media.taylordb.ai/files/old.png'],
        },
      })
      .where('id', '=', 1)
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'update',
      tableName: 'customers',
      values: {
        avatar: {
          newAttachments: [
            {
              url: 'test-path.png',
              fileType: 'image/png',
              size: 12345,
            },
          ],
          deletedUrls: ['files/old.png'],
        },
      },
    });
  });

  it('should upload attachments and return Attachment instances', async () => {
    const mockUploadResponse = [
      {
        collectionName: 'string',
        fileInformation: {
          fieldname: 'files',
          originalname: 'Designer.png',
          encoding: '7bit',
          mimetype: 'image/png',
          destination:
            '/var/bamboo/storage/bamboo-media-uploader-main/files/d2330358-ae38-40ef-b127-bd497456d488',
          filename: '31529ce5-5ef2-428d-bb63-aaf8d3e97635.png',
          path: 'files/d2330358-ae38-40ef-b127-bd497456d488/31529ce5-5ef2-428d-bb63-aaf8d3e97635.png',
          size: 1483249,
          format: 'png',
          width: 1080,
          height: 1080,
        },
        metadata: { thumbnails: [], clips: [] },
        baseId: 'fdfdfd',
        storageAdaptor: 'LOCAL',
        _id: '691ec20b164dcec7a1a981f6',
        __v: 0,
      },
    ];

    global.fetch = jest.fn().mockResolvedValue({
      ok: true,
      json: jest.fn().mockResolvedValue(mockUploadResponse),
    });

    // @ts-ignore
    const qb = createQueryBuilder<TaylorDatabase>({
      baseUrl: 'http://localhost',
      baseId: 'test-base-id',
      apiKey: 'test-api-key',
    });

    const files = [{ file: new Blob(['']), name: 'test.png' }];
    const attachments = await qb.uploadAttachments(files);

    expect(fetch).toHaveBeenCalledWith(
      'https://media.taylordb.ai/collections/default/files',
      expect.objectContaining({
        method: 'POST',
        headers: {
          Authorization: 'Bearer test-api-key',
          baseId: 'test-base-id',
        },
      }),
    );

    expect(attachments).toHaveLength(1);
    expect(attachments[0]).toBeInstanceOf(Attachment);
    expect(attachments[0].fileInformation.originalname).toBe('Designer.png');
    expect(attachments[0].toColumnValue()).toEqual({
      url: 'files/d2330358-ae38-40ef-b127-bd497456d488/31529ce5-5ef2-428d-bb63-aaf8d3e97635.png',
      fileType: 'image/png',
      size: 1483249,
    });
  });

  it('should transform attachment path strings to absolute URLs in select response', async () => {
    mockRawRequest.mockResolvedValueOnce([
      [
        {
          id: 1,
          firstName: 'Jane',
          avatar: [
            'files/bucket/31529ce5.png',
            'files/bucket/another-file.jpg',
          ],
        },
      ],
    ]);

    const result = await qb
      .selectFrom('customers')
      .select(['firstName', 'avatar'])
      .executeTakeFirst();

    expect(result).toEqual({
      id: 1,
      firstName: 'Jane',
      avatar: [
        'https://media.taylordb.ai/files/bucket/31529ce5.png',
        'https://media.taylordb.ai/files/bucket/another-file.jpg',
      ],
    });
  });

  it('should not transform non-attachment strings in select response', async () => {
    mockRawRequest.mockResolvedValueOnce([
      [
        {
          id: 1,
          firstName: 'Jane',
          lastName: 'Doe',
        },
      ],
    ]);

    const result = await qb
      .selectFrom('customers')
      .select(['firstName', 'lastName'])
      .executeTakeFirst();

    expect(result).toEqual({ id: 1, firstName: 'Jane', lastName: 'Doe' });
  });

  it('should return empty array for empty attachment field in select response', async () => {
    mockRawRequest.mockResolvedValueOnce([
      [
        {
          id: 1,
          firstName: 'Jane',
          avatar: [],
        },
      ],
    ]);

    const result = await qb
      .selectFrom('customers')
      .select(['firstName', 'avatar'])
      .executeTakeFirst();

    expect(result).toEqual({ id: 1, firstName: 'Jane', avatar: [] });
  });

  it('should transform attachment paths in a list of records', async () => {
    mockRawRequest.mockResolvedValueOnce([
      [
        { id: 1, firstName: 'Jane', avatar: ['files/bucket/a.png'] },
        { id: 2, firstName: 'John', avatar: ['files/bucket/b.png'] },
      ],
    ]);

    const result = await qb
      .selectFrom('customers')
      .select(['firstName', 'avatar'])
      .execute();

    expect(result).toEqual([
      {
        id: 1,
        firstName: 'Jane',
        avatar: ['https://media.taylordb.ai/files/bucket/a.png'],
      },
      {
        id: 2,
        firstName: 'John',
        avatar: ['https://media.taylordb.ai/files/bucket/b.png'],
      },
    ]);
  });

  it('should compile an insert query with multi-select array and execute', async () => {
    await qb
      .insertInto('orders')
      .values({
        amount: 100,
        status: 'Pending',
        tags: ['Urgent', 'Low Priority'],
      })
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'create',
      tableName: 'orders',
      createdRecords: [
        {
          amount: 100,
          status: 'Pending',
          tags: ['Urgent', 'Low Priority'],
        },
      ],
    });
  });

  it('should map collaborators to bambooCollaborators for select queries', async () => {
    await qb.selectFrom('collaborators').select(['id', 'name']).execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'bambooCollaborators',
      fields: ['id', 'name'],
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'status',
            operator: '=',
            value: 'ACTIVE',
          },
        ],
      },
    });
  });

  it('should map collaborators to bambooCollaborators for aggregate queries', async () => {
    mockRawRequest.mockResolvedValueOnce([
      [
        {
          count: 5,
          aggregates: { id: { sum: 15 } },
        },
      ],
    ]);

    await qb
      .aggregateFrom('collaborators')
      .metrics({ idSum: sum('id') })
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'aggregation',
      tableName: 'bambooCollaborators',
      aggregations: {
        id: ['sum'],
      },
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'status',
            operator: '=',
            value: 'ACTIVE',
          },
        ],
      },
    });
  });

  it('should preserve the default ACTIVE status filter when adding additional filters', async () => {
    await qb
      .selectFrom('collaborators')
      .select(['id', 'name'])
      .where('name', '=', 'John')
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'bambooCollaborators',
      fields: ['id', 'name'],
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'status',
            operator: '=',
            value: 'ACTIVE',
          },
          {
            field: 'name',
            operator: '=',
            value: 'John',
          },
        ],
      },
    });
  });

  it('should fetch the current user profile using auth.getUser', async () => {
    mockRawRequest.mockResolvedValueOnce([
      [
        {
          id: 1,
          name: 'Test User',
          emailAddress: 'test@example.com',
          avatar: 'avatar.png',
        },
      ],
    ]);

    const user = await qb.auth.getUser();

    expect(user).toEqual({
      id: 1,
      name: 'Test User',
      email: 'test@example.com',
      avatar: 'avatar.png',
    });

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];

    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'bambooCollaborators',
      fields: ['id', 'name', 'emailAddress', 'avatar'],
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'status',
            operator: '=',
            value: 'ACTIVE',
          },
          {
            field: 'externalId',
            operator: '=',
            value: 'test-user-id',
          },
        ],
      },
    });
  });

  it('should throw an error if user id is not available when calling auth.getUser', async () => {
    SocketConnection.prototype.getCurrentUserId = jest
      .fn()
      .mockResolvedValueOnce(null);

    await expect(qb.auth.getUser()).rejects.toThrow(
      'User ID not available from the connection',
    );
  });

  it('should compile a plugin action without input and execute', async () => {
    await qb.plugin('email').action('archive').execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'plugin-action',
      plugin: 'email',
      action: 'archive',
      input: {},
    });
  });

  it('should compile a plugin action with input and execute', async () => {
    mockRawRequest.mockResolvedValueOnce([{ success: true }]);

    const result = await qb
      .plugin('email')
      .action('send')
      .input({ recordId: 10, scheduledAt: 'tomorrow' })
      .execute();

    expect(result).toEqual({ success: true });
    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'plugin-action',
      plugin: 'email',
      action: 'send',
      input: {
        recordId: 10,
        scheduledAt: 'tomorrow',
      },
    });
  });

  it('should compile a plugin action inside a batch query', async () => {
    await qb
      .batch([
        qb.selectFrom('customers').select(['firstName']),
        qb.plugin('email').action('send').input({ recordId: 12 }),
      ])
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata).toHaveLength(2);
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'customers',
    });
    expect(variables.metadata[1]).toMatchObject({
      type: 'plugin-action',
      plugin: 'email',
      action: 'send',
      input: { recordId: 12 },
    });
  });

  it('should compile a plugin action inside a transaction', async () => {
    const mockRawRequest = jest
      .fn()
      .mockResolvedValueOnce({
        startTransaction: 'plugin-tx-id',
      })
      .mockResolvedValueOnce({ execute: [] })
      .mockResolvedValueOnce({ commitTransaction: true });

    SocketConnection.prototype.rawRequest = mockRawRequest;

    // @ts-ignore
    const qbTx = createQueryBuilder<TaylorDatabase>({
      baseUrl: 'http://localhost',
      baseId: 'test-base-id',
      apiKey: 'test',
    });

    await qbTx.transaction(txQb => {
      return txQb
        .plugin('email')
        .action('send')
        .input({ recordId: 5 })
        .execute();
    });

    expect(mockRawRequest).toHaveBeenCalledTimes(3);

    const executeCall = mockRawRequest.mock.calls[1];
    expect(executeCall[3]).toBe('plugin-tx-id'); // transactionId check
    const variables = executeCall[1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'plugin-action',
      plugin: 'email',
      action: 'send',
      input: { recordId: 5 },
    });
  });
});
