import { createQueryBuilder } from '../index.js';
import { SocketConnection } from '../socket-connection.js';
import {
  AutoGeneratedNumberColumnType,
  DateColumnType,
  LinkColumnType,
  NumberColumnType,
  TaylorDatabase as TaylorDatabaseOriginal,
  TextColumnType,
} from './taylorclient.types.js';

interface OrdersTable {
  id: AutoGeneratedNumberColumnType;
  createdAt: DateColumnType<false>;
  updatedAt: DateColumnType<false>;
  amount: NumberColumnType<false>;
  customer: LinkColumnType<'customers', false>;
}

interface CustomersTable {
  id: AutoGeneratedNumberColumnType;
  createdAt: DateColumnType<false>;
  updatedAt: DateColumnType<false>;
  firstName: TextColumnType<true>;
  lastName: TextColumnType<false>;
  orders: LinkColumnType<'orders', false>;
}

interface TaylorDatabase extends TaylorDatabaseOriginal {
  orders: OrdersTable;
  customers: CustomersTable;
}

jest.mock('socket.io-client', () => {
  const mockSocket = {
    on: jest.fn(),
    emit: jest.fn(),
    once: jest.fn(),
  };
  return {
    io: jest.fn(() => mockSocket),
  };
});

describe('QueryBuilder', () => {
  let mockRawRequest: jest.Mock;

  beforeEach(() => {
    mockRawRequest = jest.fn().mockResolvedValue({ execute: [] });
    SocketConnection.prototype.rawRequest = mockRawRequest;
  });

  // @ts-ignore
  const qb = createQueryBuilder<TaylorDatabase>({
    baseUrl: 'http://localhost',
    apiKey: 'test',
  });

  it('should compile a select query and execute', async () => {
    await qb
      .selectFrom('customers')
      .select(['firstName', 'lastName'])
      .where('firstName', '=', 'John')
      .orderBy('lastName', 'asc')
      .paginate(1, 10)
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'customers',
      fields: ['firstName', 'lastName'],
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'firstName',
            operator: '=',
            value: 'John',
          },
        ],
      },
      sorting: [{ field: 'lastName', direction: 'asc' }],
      pagination: { offset: 0, limit: 10 },
    });
  });

  it('should compile an insert query and execute', async () => {
    await qb
      .insertInto('customers')
      .values({
        firstName: 'Jane',
        lastName: 'Doe',
      })
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'create',
      tableName: 'customers',
      createdRecords: [{ firstName: 'Jane', lastName: 'Doe' }],
    });
  });

  it('should compile an update query and execute', async () => {
    await qb
      .update('customers')
      .set({ lastName: 'Smith' })
      .where('id', '=', 1)
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'update',
      tableName: 'customers',
      values: { lastName: 'Smith' },
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'id',
            operator: '=',
            value: 1,
          },
        ],
      },
    });
  });

  it('should compile a delete query and execute', async () => {
    await qb.deleteFrom('customers').where('id', '=', 1).execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'delete',
      tableName: 'customers',
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'id',
            operator: '=',
            value: 1,
          },
        ],
      },
    });
  });

  it('should compile a batch query and execute', async () => {
    await qb
      .batch([
        qb.selectFrom('customers').select(['firstName', 'lastName']),
        qb
          .insertInto('customers')
          .values({ firstName: 'John', lastName: 'Doe' }),
      ])
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata).toHaveLength(2);
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'customers',
    });
    expect(variables.metadata[1]).toMatchObject({
      type: 'create',
      tableName: 'customers',
    });
  });

  it('should compile an aggregate query and execute', async () => {
    await qb
      .aggregateFrom('customers')
      .groupBy('firstName', 'asc')
      .withAggregates({
        id: ['sum'],
      })
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'aggregation',
      tableName: 'customers',
      groupings: [{ field: 'firstName', direction: 'asc' }],
      aggregations: {
        id: ['sum'],
      },
    });
  });

  it('should compile a cross-table query and execute', async () => {
    await qb
      .selectFrom('customers')
      .where('orders', 'hasAnyOf', qb => qb.where('amount', '>', 100))
      .execute();

    expect(mockRawRequest).toHaveBeenCalledTimes(1);
    const variables = mockRawRequest.mock.calls[0][1];
    expect(variables.metadata[0]).toMatchObject({
      type: 'select',
      tableName: 'customers',
      filtersSet: {
        conjunction: 'and',
        filtersSet: [
          {
            field: 'orders',
            operator: 'hasAnyOf',
            value: [
              'cross-table',
              {
                conjunction: 'and',
                filtersSet: [
                  {
                    field: 'amount',
                    operator: '>',
                    value: 100,
                  },
                ],
              },
            ],
          },
        ],
      },
    });
  });

  it('should handle a successful transaction', async () => {
    const mockRawRequest = jest
      .fn()
      .mockResolvedValueOnce({
        startTransaction: 'test-transaction-id',
      })
      .mockResolvedValueOnce({ execute: [] })
      .mockResolvedValueOnce({ commitTransaction: true });

    SocketConnection.prototype.rawRequest = mockRawRequest;

    // @ts-ignore
    const qb = createQueryBuilder<TaylorDatabase>({
      baseUrl: 'http://localhost',
      apiKey: 'test',
    });

    await qb.transaction(txQb => {
      return txQb
        .insertInto('customers')
        .values({ firstName: 'John', lastName: 'Doe' })
        .execute();
    });

    expect(mockRawRequest).toHaveBeenCalledTimes(3);

    const startTransactionCall = mockRawRequest.mock.calls[0];
    expect(startTransactionCall[0]).toContain('startTransaction');

    const executeCall = mockRawRequest.mock.calls[1];
    expect(executeCall[3]).toBe('test-transaction-id');

    const commitTransactionCall = mockRawRequest.mock.calls[2];
    expect(commitTransactionCall[0]).toContain('commitTransaction');
    expect(commitTransactionCall[3]).toBe('test-transaction-id');
  });

  it('should handle a failed transaction and rollback', async () => {
    const transactionId = 'test-transaction-id-fail';
    const errorMessage = 'Something went wrong';

    const mockRawRequest = jest
      .fn()
      .mockResolvedValueOnce({ startTransaction: transactionId })
      .mockRejectedValueOnce(new Error(errorMessage))
      .mockResolvedValueOnce({ rollbackTransaction: true });

    SocketConnection.prototype.rawRequest = mockRawRequest;

    // @ts-ignore
    const qb = createQueryBuilder<TaylorDatabase>({
      baseUrl: 'http://localhost',
      apiKey: 'test',
    });

    await expect(
      qb.transaction(txQb => {
        return txQb
          .insertInto('customers')
          .values({ firstName: 'John', lastName: 'Doe' })
          .execute();
      }),
    ).rejects.toThrow(errorMessage);

    expect(mockRawRequest).toHaveBeenCalledTimes(3);

    const startTransactionCall = mockRawRequest.mock.calls[0];
    expect(startTransactionCall[0]).toContain('startTransaction');

    const executeCall = mockRawRequest.mock.calls[1];
    expect(executeCall[3]).toBe(transactionId);

    const rollbackTransactionCall = mockRawRequest.mock.calls[2];
    expect(rollbackTransactionCall[0]).toContain('rollbackTransaction');
    expect(rollbackTransactionCall[3]).toBe(transactionId);
  });

  it('should not have transaction method within a transaction', async () => {
    const mockRawRequest = jest
      .fn()
      .mockResolvedValueOnce({
        startTransaction: 'test-transaction-id-no-nested',
      })
      .mockResolvedValueOnce({ commitTransaction: true });

    SocketConnection.prototype.rawRequest = mockRawRequest;

    // @ts-ignore
    const qb = createQueryBuilder<TaylorDatabase>({
      baseUrl: 'http://localhost',
      apiKey: 'test',
    });

    await qb.transaction(async txQb => {
      expect(txQb).not.toHaveProperty('transaction');
    });

    expect(mockRawRequest).toHaveBeenCalledTimes(2);
  });
});
