import {ColumnType, NumberColumnType, TextColumnType} from '@taylordb/shared';
import {createQueryBuilder} from './query-builder.js';

// --- Sample Database Definition ---
// This would typically be generated by your CLI
interface CustomersTable {
  id: NumberColumnType;
  name: TextColumnType;
  email: TextColumnType;
  phone: TextColumnType;
  orders: ColumnType<any, any, any, 'link'>; // Simplified link type
}

interface OrdersTable {
  id: NumberColumnType;
  address: TextColumnType;
  customerId: NumberColumnType;
}

interface TaylorDatabase {
  [key: string]: any;
  customers: CustomersTable;
  orders: OrdersTable;
}
// --- End of Sample Database Definition ---

const qb = createQueryBuilder<TaylorDatabase>();

// Example 1: Simple select with a where clause
const simpleSelect = qb
  .selectFrom('customers')
  .select(['id', 'name', 'email'])
  .where('email', '=', 'test@example.com')
  .compile();

console.log('--- Simple Select ---');
console.log(simpleSelect);

// Example 2: Select with multiple conditions (AND)
const andConditions = qb
  .selectFrom('customers')
  .select(['id', 'name'])
  .where('name', '=', 'John Doe')
  .where('phone', '!=', '555-1234')
  .compile();

console.log('\n--- AND Conditions ---');
console.log(andConditions);

// Example 3: Select with OR conditions
const orConditions = qb
  .selectFrom('customers')
  .select(['id', 'name'])
  .where('name', '=', '2')
  .where(qb => qb.where('name', '=', '3').orWhere('name', '=', '4'))
  .orWhere('email', 'contains', '@example.com')
  .compile();

console.log('\n--- OR Conditions ---');
console.log(orConditions);

// Example 4: Nested conditions
const nestedConditions = qb
  .selectFrom('customers')
  .select(['id', 'name'])
  .where(qb =>
    qb.where('name', 'startsWith', 'J').where('email', 'endsWith', '.com')
  )
  .orWhere(qb => qb.where('phone', 'contains', '555'))
  .compile();

console.log('\n--- Nested Conditions ---');
console.log(nestedConditions);

// Example 5: Relational select with useLink
const relationalSelect = qb
  .selectFrom('customers')
  .select([
    'id',
    'name',
    qb =>
      qb
        .useLink('orders')
        .select(['id', 'address'])
        .where(qb => qb.where('address', '=', '123 Main St')),
  ])
  .where('id', '=', 1)
  .compile();

console.log('\n--- Relational Select ---');
console.log(relationalSelect);
