#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Running tests and linter before push..."
pnpm test && pnpm run lint

if [ $? -ne 0 ]; then
  echo "Pre-push checks failed. Please fix the issues before pushing."
  exit 1
fi

echo "Pre-push checks passed."
exit 0
